version: "3"

services:
  coderoso:
    image: coderoso:latest
    container_name: coderoso
    restart: always
    ports:
      - 3000:3000

  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - coderoso
